
version: 2

models:
    - name: chicagocrime_details
      description: "Generic testing - severity check is used to give us only warning when null values are found more than 10 - else it would have stopped testing and thrown error"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null:
                    config:                 
                      severity: warn
                      error_if: ">10"
                      



    - name: chicagocrime_description
      description: "Great Expectations testing"
      columns:
        - name: description_id
          tests:
            - dbt_expectations.expect_column_to_be_unique
        - name: crime_description
          tests:
            - dbt_expectations.expect_column_values_to_not_be_null


    - name: chicagocrime_location
      columns:
        - name: location_id
          tests:
            - dbt_utils.at_least_one
        - name: location_description
          tests:
            - dbt_utils.non_null_values
        - name: location
          tests:
            - dbt_utils.non_empty_strings



    - name: dim_chicagocrimedata
      description: "Check the unique values in arrest column when the date starts from 2010-12-30"
      columns:
        - name: ARREST
          tests:
            - unique:
                config:
                  where: "date > '2010-12-30'"  
                  store_failures: true
                  schema: "DBT_PRACTISE"

#            - arrestments_true          
# This is the Singular converted into generic test and arrestments_true is used as a macro and its roots lies in test/generic


    - name: chicagocrime_arrestments
      description: "configuration for severity for generic testing can done by this way - it will show error when there are non unique values grater than 50"
      columns:
        - name: ARRESTMENT_ID
          tests:
            - unique:
                config:
                  severity: error
                  error_if: '>10'
                

